# Generated by Django 3.1.1 on 2020-12-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20201203_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(null=True, related_name='_comment_replies_+', to='news.Comment'),
        ),
    ]
