# Generated by Django 3.1.1 on 2020-11-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201119_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_Date',
            new_name='pub_date',
        ),
    ]
