# Generated by Django 3.1.1 on 2020-11-27 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201127_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile_pic',
        ),
    ]
