# Generated by Django 3.1.1 on 2020-11-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201119_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='pub_Date',
        ),
    ]
